config/routes.rb
Rails.application.routes.draw do

  resources :photos do
    collection {post :sort}
  end
 match ':controller(/:action(/:id))', :via => [:get, :post]

end

app/models/internal_property.rb
class InternalProperty < ActiveRecord::Base
	belongs_to :users
	has_many   :photos

	# mount_uploader :image, ImageUploader

	scope :sorted, lambda { order("name ASC") }

end

app/models/photo.rb
class Photo < ActiveRecord::Base

	belongs_to :internal_property
	# mount_uploader :file_name, ImageUploader



	mount_uploader :image, ImageUploader

	scope :sorted, lambda { order("order ASC") }

	acts_as_list

end

app/models/user.rb
class User < ActiveRecord::Base

	has_many :internal_properties

	scope :sorted, lambda { order("last_name ASC, first_name ASC") }

	 def name
    "#{first_name} #{last_name}"
    # Or: first_name + ' ' + last_name
    # Or: [first_name, last_name].join(' ')
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/internal_properties_controller.rb
class InternalPropertiesController < ApplicationController
layout "admin"

  def index
    @properties = InternalProperty.sorted
  end

  def show
     @property = InternalProperty.find(params[:id])
  end

  def new
     @users = User.order("first_name ASC")
     @property = InternalProperty.new
  end

  def create
    property = InternalProperty.new(property_params)
    if property.save
      if property_params[:image].present?
        property_params[:image].each do |i|
          photo = Photo.new(:image => i, :internal_property_id => property.id)
          photo.save
       end
      end
      flash[:notice] = 'New Property Created.'
      redirect_to(:action => 'index')
    else
      render("new")
    end
  end

    def edit
    @users = User.order("first_name ASC")
    @property = InternalProperty.find(params[:id])
    #@photos = @property.photos
    @photos = @property.photos.order(:position)
  end

  def update
    @property = InternalProperty.find(params[:id])
    if @property.update_attributes(property_params)
       if property_params[:image].present?
        property_params[:image].each do |i|
          photo = Photo.new(:image => i, :internal_property_id => @property.id)
          photo.save
       end
      end
      flash[:notice] = 'Property updated.'
      redirect_to(:action => 'index')
    else
      render("edit")
    end
  end

  def delete
    @property = InternalProperty.find(params[:id])
  end

  def destroy
    InternalProperty.find(params[:id]).destroy
    flash[:notice] = "Property Deleted"
    redirect_to(:action => 'index')
  end

  private

  def property_params
    params.require(:property).permit(:name, :price, :address, :description, :short_description, :user_id, image: [])
  end

end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController


	def sort
		params[:photo].each_with_index do |id, index|
    	Photo.update(id, position: index+1)
  	end
		render nothing: true
	end

	def destroy
		photo = Photo.find(params[:id])
		prop_id = photo.internal_property_id
    photo.destroy
    flash[:notice] = "Photo Deleted"
    redirect_to(:controller => 'internal_properties', :action => 'edit', :id => prop_id)
  end



end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  layout "admin"

  def index
    @users = User.sorted
  end

  def show
     @user = User.find(params[:id])
  end

  def new
     @admin_user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = 'Admin user created.'
      redirect_to(:action => 'index')
    else
      render("new")
    end
  end

    def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:notice] = 'User updated.'
      redirect_to(:action => 'index')
    else
      render("edit")
    end
  end

  def delete
    @user = User.find(params[:id])
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:notice] = "User destroyed"
    redirect_to(:action => 'index')
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name,
      :title, :email,  :password, :bio)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/internal_properties_helper.rb
module InternalPropertiesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/internal_properties/_form.html.erb
<div class="form-group">
    <%= f.label(:name) %>
    <%= f.text_field(:name, :class => 'form-control') %>
</div>
<div class="form-group">
    <%= f.label(:price) %>
    <%= f.text_field(:price, :class => 'form-control') %>
</div>
<div class="form-group">
   <%= f.label(:address) %>
    <%= f.text_field(:address, :class => 'form-control') %>
</div>
<div class="form-group"> 
  <%= f.label(:description) %>
  <%= f.text_area(:description, :class => 'form-control') %>
</div>
<div class="form-group">  
  <%= f.label(:short_description) %>
  <%= f.text_field(:short_description, :class => 'form-control') %>
</div>
<div class="form-group">  
  <%= f.label(:user_id, "Agent") %>
  <%= f.select(:user_id, @users.map {|u| [u.first_name, u.id]}, :class => 'form-control') %>
</div>

<div class="form-group">  
  <%= f.label(:image, "Photos") %>
  <%= f.file_field(:image, :multiple => true, :class => 'form-control') %>
</div>

app/views/internal_properties/delete.html.erb
<% @page_title = "Delete Property: #{@property.name}" %>

<%= link_to("<< Back to List", {:action => 'index'}, :class => 'back-link') %>

<div class="user delete">
  <h2>Delete Admin User</h2>

  <%= form_for(:property, :url => {:action => 'destroy', :id => @property.id}) do |f| -%>

    <p>Are you sure you want to permanently delete this admin user?</p>

    <p class="reference-name"><%= @property.name %></p>

    <div class="form-buttons">
      <%= submit_tag("Delete Property") %>
    </div>

  <% end %>
</div>

app/views/internal_properties/edit.html.erb
<% @page_title = "Edit Admin User: #{@property.name}" -%>

<%= link_to("<< Back to List", {:action => 'index'}, :class => 'back-link') %>


  <h2>Edit <%= @property.name %></h2>

  <div class="row">
	 <div class="col-xs-6">
  <h2><%= @property.name %></h2>
  <%= form_for(:property, :html => {:multipart => true}, :url => {:action => 'update', :id => @property.id}) do |f| %>

    <%= render(:partial => 'form', :locals => {:f => f} ) %>


    <%= submit_tag('Update Property') %>

  <% end %>
 	</div>
 	 <div class="col-xs-6">
 	 <ul id="photos" data-update-url="<%= sort_photos_url %>">
 	 	<% @photos.each do |photo| %>
		  <%= content_tag_for :li, photo do %>
		 		<%= image_tag photo.image_url(:thumb).to_s %><br>
		 				 		<%= link_to("Delete", photo_path(photo), method: :delete) %>
		 		<%#= link_to("Delete", {:controller => 'photos', :action => 'destroy', :id => photo.id, :prop_id => @property.id, :method => :delete}) %>
			<%end%>
		<% end %>
	</ul>
	</div>
</div>

  
</div>

app/views/internal_properties/index.html.erb
<% @page_title = "Admin Users List" %>

       

  <div class="row">
    <div class="col-xs-10">
      <h2 class="pull-left">Properties</h2>
    </div>
    <div class="col-xs-2">
      <%= link_to('Add New Property', {:action => 'new'}, :class => 'btn btn-default pull-right', :style => 'margin-top:20px;') %>
    </div>
  </div>

  
  <div class="row">
    <div class="col-xs-12">
     <%= pluralize(@properties.size, 'property') %> found
    </div>
  </div>

<div class="row">
  <div class="col-xs-12">
    <table class="table">
      <tr>
        <th>Name</th>
         <th>Price</th>
        <th>Address</th>
        <th>Actions</th>
      </tr>
      <% @properties.each do |property| %>
      <tr class="<%= cycle('odd', 'even') %>">
      	<td><%= link_to(property.name, {:action => 'show', :id => property.id}, :class => 'btn btn-info') %></td>
        <td><%= number_to_currency(property.price, :unit => "$") %></td>
        <td><%= property.address %></td>
      
        <td>
          <%= link_to('Edit', {:action => 'edit', :id => property.id}, :class => 'btn btn-default') %>
          <%= link_to('Delete', {:action => 'delete', :id => property.id}, :class => 'btn btn-default') %>
        </td>
      </tr>
      <% end %>
    </table>
  </div>
</div>

app/views/internal_properties/new.html.erb
<% @page_title = 'Create User' %>

<span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span> <%= link_to("Back to List", {:action => 'index'}, :class => '') %>

<div class="user new">
  <h2>Create Property</h2>

  <%= form_for(:property, :url => {:action => 'create'}) do |f| %>

    <%= render(:partial => 'form', :locals => {:f => f} ) %>

  
      <%= submit_tag('Create Property') %>


  <% end %>
</div>

app/views/internal_properties/show.html.erb
<% @page_title = 'Create User' %>

<%= link_to("<< Back to List", {:action => 'index'}, :class => 'back-link') %>

<div class="row">
	 <div class="col-xs-6">
  <h2><%= @property.name %></h2>
 	</div>
 	 <div class="col-xs-6">
 	 <% @property.photos.each do |photo| %>
		 <%= image_tag photo.image_url(:thumb).to_s %>
		<% end %>
	</div>
</div>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-default navbar-static">
  <div class="container-fluid">
		<div class="navbar-header">
		<a class="navbar-brand" href="/">Property Manager</a>
			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
				<span class="sr-only">Toggle Nav</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
		</div>

   	<ul class="nav navbar-nav navbar-right collapse navbar-collapse">
      <li><%= link_to("Agents", {:controller => 'users', :action => 'index'}) %></li>
      <li><%= link_to("Properties", {:controller => 'internal_properties', :action => 'index'}) %></li>
      <li><%= link_to("Photos", {:controller => 'photos', :action => 'index'}) %></li>
    </ul>

   </div>
</nav>

app/views/layouts/admin.html.erb
<!DOCTYPE html>

<html>
  <head>
  <title>Property</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
	</head>
  <body>

   <%= render(:partial => 'layouts/nav') %>

    <div id="main-container" class="container-fluid">
    
    	<% if !flash[:notice].blank? %>
			 <div class="row">
        <div class="col-xs-12">
					<%=flash[:notice] %>
				</div>
			<%end%>
			</div>
       
      
      <div class="container-fluid">
 					<%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html>
  <head>
  <title>Property</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
	</head>
  <body>

  <%= render 'nav' %>

    <div id="main-container" class="container">
      <div class="row">
        <div class="col-xs-3">
          <h3>Tealeaf Academy Todo</h3>
        </div>
        <div class="col-xs-9">
         <%= yield %>
        </div>
      </div>
    </div>

  </body>
</html>

app/views/users/_form.html.erb
<div class="form-group">
    <%= f.label(:first_name) %>
    <%= f.text_field(:first_name, :class => 'form-control') %>
</div>
<div class="form-group">
    <%= f.label(:last_name) %>
    <%= f.text_field(:last_name, :class => 'form-control') %>
</div>
<div class="form-group">
   <%= f.label(:title) %>
    <%= f.text_field(:title, :class => 'form-control') %>
</div>
<div class="form-group">  
  <%= f.label(:email) %>
  <%= f.text_field(:email, :class => 'form-control') %>
</div>
<div class="form-group">  
  <%= f.label(:password) %>
  <%= f.password_field(:password, :class => 'form-control') %>
</div>
<div class="form-group"> 
  <%= f.label(:bio) %>
  <%= f.text_area(:bio, :class => 'form-control') %>
</div>

app/views/users/delete.html.erb
<% @page_title = "Delete User: #{@user.name}" %>

<%= link_to("<< Back to List", {:action => 'index'}, :class => 'back-link') %>

<div class="user delete">
  <h2>Delete Admin User</h2>

  <%= form_for(:user, :url => {:action => 'destroy', :id => @user.id}) do |f| -%>

    <p>Are you sure you want to permanently delete this  user?</p>

    <p class="reference-name"><%= @user.name %></p>

    <div class="form-buttons">
      <%= submit_tag("Delete User") %>
    </div>

  <% end %>
</div>

app/views/users/edit.html.erb
<% @page_title = "Edit Admin User: #{@user.name}" -%>

<%= link_to("<< Back to List", {:action => 'index'}, :class => 'back-link') %>


  <h2>Edit <%= @user.name %></h2>

  <%= form_for(:user, :url => {:action => 'update', :id => @user.id}) do |f| %>

    <%= render(:partial => 'form', :locals => {:f => f} ) %>


    <%= submit_tag('Update Agent') %>

  <% end %>
</div>

app/views/users/index.html.erb
<% @page_title = "Admin Users List" %>

       

  <div class="row">
    <div class="col-xs-10">
      <h2 class="pull-left">Agents</h2>
    </div>
    <div class="col-xs-2">
      <%= link_to('Add New Agent', {:action => 'new'}, :class => 'btn btn-default pull-right', :style => 'margin-top:20px;') %>
    </div>
  </div>

  
  <div class="row">
    <div class="col-xs-12">
     <%= pluralize(@users.size, 'agent') %> found
    </div>
  </div>

<div class="row">
  <div class="col-xs-12">
    <table class="table">
      <tr>
        <th>Agent</th>
         <th>Title</th>
        <th>Email</th>
        <th>Bio</th>
        <th>Actions</th>
      </tr>
      <% @users.each do |user| %>
      <tr class="<%= cycle('odd', 'even') %>">
      	<td><%= link_to(user.name, {:action => 'show', :id => user.id}, :class => 'btn btn-info') %></td>
      
        <td><%= user.title %></td>
        <td><%= mail_to(user.email) %></td>
        <td><%= truncate(user.bio, :limit => 10,  :omission => "...")%></td>
        <td>
          <%= link_to('Edit', {:action => 'edit', :id => user.id}, :class => 'btn btn-default') %>
          <%= link_to('Delete', {:action => 'delete', :id => user.id}, :class => 'btn btn-default') %>
        </td>
      </tr>
      <% end %>
    </table>
  </div>
</div>

app/views/users/new.html.erb
<% @page_title = 'Create User' %>

<span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span> <%= link_to("Back to List", {:action => 'index'}, :class => '') %>

<div class="user new">
  <h2>Create Agent</h2>

  <%= form_for(:user, :url => {:action => 'create'}) do |f| %>

    <%= render(:partial => 'form', :locals => {:f => f} ) %>

  
      <%= submit_tag('Create User') %>


  <% end %>
</div>

app/views/users/show.html.erb
<% @page_title = 'Create User' %>

<%= link_to("<< Back to List", {:action => 'index'}, :class => 'back-link') %>

<div class="user new">
  <h2><%= @user.name %></h2>

  <p><% @user.internal_properties.map do |prop| %>
  	<%= prop.name %><br>
  	<% end %></p>
</div>